### ISSUE TITLE
Slicer instructions - incomplete?

### ISSUE THREAD

**Issue by mathieuboudreau** [shimming-toolbox/b0-fieldmap-realistic-simulation#7]
https://github.com/shimming-toolbox/b0-fieldmap-realistic-simulation/blob/f166ff5f38b2c6ea46ebe020fcb0313add778e7f/smoothing_procedure.py#L25-L30

Hi @CharlesPageot  - I installed Slicer and am trying to replicate your smoothed skulls, however the instructions in these files are not working for me. Am I missing additional setup steps to run your script?

```shell

(base) mathieuboudreau@Mathieus-MacBook-Pro b0-fieldmap-realistic-simulation %  /Applications/Slicer.app/Contents/MacOS/Slicer --python-script smoothing_procedure.py -m data/sub-amuAL_T1w.nii.gz -s data/sub-amuAL_T1w_label-brain_dseg.nii.gz -o data/slicer_smoothing_output.nii.gz
Error #1 while writing setting "Modules/AdditionalPaths"
Error #1 while writing setting "Modules/IgnoreModules"
Error #1 while writing setting "Extensions/ManagerEnabled"
Error #1 while writing setting "Extensions/ServerUrl"
Error #1 while writing setting "Extensions/FrontendServerUrl"
Error #1 while writing setting "Extensions/InstallPath"
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Switch to module:  "Welcome"
Populating font family aliases took 73 ms. Replace uses of missing font family ".AppleSystemUIFont" with one that exists to avoid this cost. 
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'click'
Switch to module:  ""
Switch to module:  ""

```

`click` was installed locally through `pipy` in my `base`, but maybe Slicer doesn't see that path

**Comment by CharlesPageot** [comment]
Yeah it looks like Slicer doesn't see it. Maybe if you try to install `click` inside Slicer's embedded Python environment? 

![image](https://github.com/user-attachments/assets/90a664a1-7651-45c0-b169-29b795db817e)
